import { memo, useMemo, useState } from 'react';
import ArrowMarker from './ArrowMarker';
import DiagramControls from './DiagramControls';
import StateNode from './StateNode';
import TransitionEdge from './TransitionEdge';
import { collectDeadStates, groupTransitions, layoutStates, simulationHighlights } from './diagramUtils';

function StateDiagram({ automaton, simulation }) {
  const [zoom, setZoom] = useState(1);
  const { layout, edges, deadStates, highlights } = useMemo(() => { const deadStates = collectDeadStates(automaton); return { layout: layoutStates(automaton, deadStates), edges: groupTransitions(automaton), deadStates, highlights: simulationHighlights(automaton, simulation) }; }, [automaton, simulation]);
  return <section aria-labelledby="state-diagram-title"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="state-diagram-title" className="font-display text-lg font-semibold">State Diagram</h2><p className="mt-1 text-sm text-ink-muted dark:text-ink-darkMuted">A vector view of the same transitions shown in the table.</p></div><DiagramControls zoom={zoom} onZoom={setZoom} onReset={() => setZoom(1)} /></div><div className="mt-5 overflow-auto rounded-xl border border-line bg-surface-muted p-3 dark:border-line-dark dark:bg-canvas-dark"><svg role="img" aria-label={`${automaton.kind.toUpperCase()} state diagram with ${automaton.states.length} states`} viewBox={`0 -90 ${layout.width} ${layout.height + 90}`} style={{ width: `${layout.width * zoom}px`, minWidth: `${Math.min(layout.width, 440)}px`, height: `${layout.height * zoom}px` }} className="mx-auto block transition-[width,height] duration-200"><defs><ArrowMarker /></defs><g className="text-ink-muted dark:text-ink-darkMuted"><path d={`M 18 ${layout.positions[automaton.startState].y} L ${layout.positions[automaton.startState].x - 35} ${layout.positions[automaton.startState].y}`} fill="none" stroke="currentColor" strokeWidth="1.8" markerEnd="url(#autofa-arrowhead)" /></g>{edges.map(edge => <TransitionEdge key={edge.key} edge={edge} positions={layout.positions} edges={edges} active={highlights.edges} />)}{automaton.states.map(state => <StateNode key={state} state={state} point={layout.positions[state]} accepting={(automaton.acceptingStates ?? automaton.acceptStates ?? []).includes(state)} dead={deadStates.has(state)} active={highlights.states.has(state)} />)}</svg></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-ink-muted dark:text-ink-darkMuted" aria-label="Diagram legend"><span className="flex items-center gap-1.5"><i className="size-3 rounded-full border border-ink-muted" />Normal state</span><span className="flex items-center gap-1.5"><i className="size-3 rounded-full border-2 border-success ring-2 ring-success-soft" />Accept state</span><span className="flex items-center gap-1.5"><i className="size-3 rounded-full border border-danger bg-danger-soft" />Dead state</span><span>Arrow: transition</span></div>{simulation && <p className={`mt-3 text-sm font-medium ${simulation.accepted ? 'text-success' : 'text-danger'}`}>Simulation path highlighted: {simulation.accepted ? 'accepted' : 'rejected'}.</p>}</section>;
}
export default memo(StateDiagram);